project:
  type: website

website:
  title: 'Robert Ngabo'
  navbar:
    right:
      - icon: github
        href: https://github.com/ngaboindev
      - icon: twitter
        href: https://twitter.com/robert_ngabo
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
